name: Build
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      
    - name: Checkout
      uses: actions/checkout@master

    - name: Test
      run: ./gradle-docker.sh build
